package timenexus.utils;

/*
 * Class to throw exceptions generated by TimeNexus.
 * @author Michaël Pierrelée, michael.pierrelee@univ-amu.fr
 */
public class MlnException extends Exception {
	
	private static final long serialVersionUID = 1L;
	// message type of JOptionPane (.ERROR_MESSAGE, .WARNING_MESSAGE...) if it needs to be displayed into a dialog
	private int messageType;
	// title of the message dialog if it needs to be displayed
	private String messageTitle;
	
	/*
	 * Customize an exception so it can be displayed into a message dialog if needed.
	 * @param title of the exception
	 * @param message of the dialog
	 * @param message type of JOptionPane (.ERROR_MESSAGE, .WARNING_MESSAGE...)  
	 */
	public MlnException( String message, String messageTitle, int messageType ) {
		super(message);
		this.messageTitle = messageTitle;
		this.messageType = messageType;
	}
	
	/*
	 * Customize an exception so it can be displayed into a message dialog if needed.
	 * @param title of the exception
	 * @param message of the dialog
	 * @param message type of JOptionPane (.ERROR_MESSAGE, .WARNING_MESSAGE...)
	 * @param previous catched exception
	 */
	public MlnException( String message, String messageTitle, int messageType, Throwable cause ) {
		super(message, cause);
		this.messageTitle = messageTitle;
		this.messageType = messageType;
	}
	
	/*
	 * Get the message type of JOptionPane.
	 */
	public int getMessageType() {
		return messageType;
	}
	
	/*
	 * Get the title of the exception.
	 */
	public String getMessageTitle() {
		return messageTitle;
	}

}
